app/models.py
from app import db


class Items(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), nullable=False)
    d_no = db.Column(db.String(150), nullable=False)
    rate = db.Column(db.String(150), nullable=False)
    final_stones = db.Column(db.String(150), nullable=False)
    img = db.Column(db.String(150), nullable=False)

    # def as_dict(self):
    #     return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    # def __repr__(self):        
    #     return json.dumps({c.name: getattr(self, c.name) for c in self.__table__.columns})
    #     # return f"< Vendor Name : {self.name} >"


class Users(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), nullable=False)
    phone_number = db.Column(db.Integer, nullable=False)
    books = db.relationship('Book', backref='users', lazy=True)

    # def as_dict(self):
    #     return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    def __repr__(self):
    #    return json.dumps({c.name: getattr(self, c.name) for c in self.__table__.columns})
        return f"< Name : {self.name} > ---->>> < Book : {len(self.books)} >"


class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    qty = db.Column(db.String(100), nullable=False)
    detail = db.Column(db.String(100), nullable=False)
    rate = db.Column(db.String(100), nullable=False)
    total = db.Column(db.String(100), nullable=False)
    customer_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    # def as_dict(self):
    #     return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    def __repr__(self):
    #    return json.dumps({c.name: getattr(self, c.name) for c in self.__table__.columns})
        return f"<Cutomer_id : {self.customer_id} Book id : {self.id} >"

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
from os import path

db = SQLAlchemy()
ma = Marshmallow()
DB_NAME = "manage.db" 

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'this_is_seceret_key'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    #intialize the database
    db.init_app(app)
    ma.init_app(app)       

    #importing both blueprint from auth and views.py files
    from .views import views
    
    #registering blueprint
    app.register_blueprint(views,url_prefix='/')

    create_database(app)

    return app

def create_database(app):
    #check if database is exists and if not exists create the database
    if not path.exists('app/' + DB_NAME) : 
        db.create_all(app=app)
        print("databse created!")

app/views.py
from flask import Blueprint
from .helper import *
from .customer import *
from .vendors import *


views = Blueprint('views', __name__)

@views.route('/')
def home():
        
    return render_template(
                        'home.html'
                        )

views.add_url_rule('/create-customer',view_func=create_customer,methods=['GET','POST'])

views.add_url_rule('/update/<int:id>/customer', view_func=update_customer,methods = ['GET','POST'])

views.add_url_rule('/delete/<int:id>/customer',view_func=delete_customer)

views.add_url_rule('/customer-details',view_func=customer_details)        

views.add_url_rule('/view/<name>',view_func=view)

views.add_url_rule('/upload',view_func=upload , methods=['GET','POST'])

views.add_url_rule('<name>/<int:id>/update',view_func=update, methods = ['GET','POST'])

views.add_url_rule('<name>/<int:id>/delete',view_func=delete)

views.add_url_rule('/customer-entry',view_func=book_entry ,methods=['GET','POST'])

views.add_url_rule('/customer-view/<int:id>',view_func=cust_entry_view)

views.add_url_rule('/delete/<int:id>',view_func=delete_entry)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %} Home {% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/home.png') }}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
</head>

<body>

    <!-- Responsive navbar-->
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <h1><a class="navbar-brand" href="{{ url_for('views.home') }}">Collections</a></h1>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('views.home') }}">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Vendors
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{{ url_for('views.view', 
                                name = 'jigarbhai') }}">Jigarbhai</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.view', 
                                name = 'kartikbhai') }}">Kartikbhai</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.view', 
                                name = 'mohanbhai') }}">Mohanbhai</a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Customers
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{{ url_for('views.create_customer') }}">Create New Customer</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.customer_details') }}">Customer Details</a></li>
                                <li><a class="dropdown-item" href="{{ url_for('views.book_entry') }}">Create Book Entry</a></li>                                                          
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="{{url_for('views.upload')}}">Upload</a></li>
                    </ul>
                </div>
            </div>
        </nav><br>

    {% block content %} {% endblock %}
    <br>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">&copy; Collections | All Rights Reserved | 2022</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

app/templates/book/cust_entry_view.html
{% extends 'base.html' %}

{% block title %} Book View {% endblock %}

{% block content %}

<div class="d-flex justify-content-left table">
  <h5><a href="{{ url_for('views.customer_details') }}"><u> Back </u></a></h5>
</div>

<div class="d-flex justify-content-center table">
    <h1><u>Name :- {{ name }}</u></h1>
</div>

<div class="container">
<table class="table table-sm align-middle table-bordered table-hover table-responsive">
    <thead class="text-center vertical-align: middle;">      
      <tr>
        <th scope="col">No.</th>
        <th scope="col">Quantity</th>
        <th scope="col">Rate</th>
        <th scope="col">Total</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody class="text-center vertical-align: middle;">
      {% for book in books %}
      <tr>
        <!-- <h1>{{ book.users.name }}</h1> -->
        <td scope="row">{{ loop.index }}</td>
        <td><b>{{ book.qty }}</b><br>{{ book.detail }}</td>
        <td>{{ book.rate }}</td>
        <td>{{ book.total }}</td>
        <td><a href="{{ url_for('views.delete_entry' , id=book.id) }}"><button class="btn btn-danger">Delete</button></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <tfoot>
    <div class="align-right">
    {% if gr_total %}
      <h3>Grand total :- {{ gr_total }}</h3>
    {% endif %}
  </tfoot>
</div>
</div>

{% endblock %}

app/templates/book/entry.html
{% extends 'base.html' %}

{% block title %} customer-entry {% endblock %}

{% block content%}

<div class="row text-center">
  {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
      {% for category, message in messages %}
  <div class="alert alert-{{category}} text-center alter-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
      {% endfor %}
    {% endif %} 
  {% endwith %}
</div>

<div class="container">
    <div class="row">
    <form action="#" method="post" autocomplete="off" class="row g-3" enctype="multipart/form-data">
      <select name="customer_id" class="form-select" aria-label="Default select example">
        <option selected>Select Customer</option>
        {% for name in names %}
        <option value="{{ name.id }}">{{ name.name }}</option>
        {% endfor %}
    </select>
      <div class="col-8">
        <label for="inputEmail4" class="form-label">Quantity </label>
        <input type="text" name="qty" class="form-control" id="qty" placeholder="Quantity" required>
      </div>
      <div class="col-8">
        <label for="inputEmail4" class="form-label">Description :-  </label>
        <input type="text" name="detail" class="form-control" id="detail" placeholder="Details">
      </div>
      <div class="col-8">
        <label for="inputAddress" class="form-label">Rate :- </label>
        <input type="text" name="rate" onchange="final_total(this)" class="form-control" id="rate" placeholder="Rate" required>
      </div>
      <div class="col-8">
        <label for="inputAddress" class="form-label">Total :- </label>
        <input type="text" name="total" class="form-control" id="total" placeholder="Total" required>
      </div>
      <div class="col-12">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}

app/templates/customer/create_customer.html
{% extends "base.html" %}

{% block title %} Create New Customer {% endblock %}

{% block content %}

<div class="container">
    <form method="post" autocomplete="off" class="row g-3" enctype="multipart/form-data">
      <div class="col-md-4">
        <label for="inputEmail4" class="form-label">Customer Name :- </label>
        <input type="text" name="name" class="form-control" id="name" placeholder="Name" required>
        <span></span>
      </div>
      <div class="col-md-4">
        <label for="inputEmail4" class="form-label">Phone Number :- </label>
        <input type="text" name="phone_number" class="form-control" id="phone_number" placeholder="01234567890" required>
        <span></span>
      </div>
      <div class="col-12">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>

{% endblock %}

app/templates/customer/customer_details.html
{% extends "base.html" %}

{% block title %} Customer Details {% endblock %}

{% block content %}

<div class="row text-center">
  {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
      {% for category, message in messages %}
  <div class="alert alert-{{category}} text-center alter-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
      {% endfor %}
    {% endif %} 
  {% endwith %}
</div>

{% if users|length == 0 %}
<div class="alert alert-warning text-center alter-dismissible fade show" role="alert">
    Customer not found. <a href="{{ url_for('views.create_customer') }}" class="alert-link">Click here to create new customer</a>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
{% endif %}

<div class="row">
  {% for user in users %}
  <div class="col-sm-4">
    <div class="card">
      <div class="card-body">
        <a href="{{ url_for('views.update_customer', id=user.id) }}"><button type="button" class="btn btn-secondary">Update</button></a>
        <a href="{{ url_for('views.delete_customer', id=user.id) }}"><button type="button" class="btn btn-danger">delete</button></a><br><br>
        <h1 class="card-title">Name : {{ user.name.capitalize() }}</h1>
        <p class="card-text">{{ user.phone_number }}</p>
        <a href="{{ url_for('views.cust_entry_view',id=user.id) }}" class="btn btn-primary">View Book</a>
      </div>
    </div><br>
  </div>
  {% endfor %}
</div>

{% endblock %}

app/templates/customer/update_customer.html
{% extends "base.html" %}

{% block title %} Update Customer {% endblock %}

{% block content %}

<div class="row text-center">
    {% with messages = get_flashed_messages(with_categories=true) %} 
      {% if messages %} 
        {% for category, message in messages %}
    <div class="alert alert-{{category}} text-center alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
        {% endfor %}
      {% endif %} 
    {% endwith %}
  </div>

<div class="container">
    <form method="post" autocomplete="off" class="row g-3" enctype="multipart/form-data">
      <div class="col-md-4">
        <label for="inputEmail4" class="form-label">Customer Name :- </label>
        <input type="text" value="{{ user.name }}" name="name" class="form-control" id="name" placeholder="Name" required>
        <span></span>
      </div>
      <div class="col-md-4">
        <label for="inputEmail4" class="form-label">Phone Number :- </label>
        <input type="text" value="{{ user.phone_number }}" name="phone_number" class="form-control" id="phone_number" placeholder="01234567890" required>
        <span></span>
      </div>
      <div class="col-12">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
  </div>

{% endblock %}

app/templates/home.html
{% extends "base.html" %}

{% block content %}
<!-- Header-->
<header class="py-5">
    <div class="container px-lg-5">
        <div class="p-4 p-lg-5 bg-light rounded-3 text-center" style="border-top: 1px solid black;">
            <div class="m-4 m-lg-5">
                <h1 class="display-5 fw-bold">A warm welcome!</h1>
                <p class="fs-4">Here are the Collections of All the Items and Rates.</p>
            </div>
        </div>
    </div>
</header>
<!-- Page Content-->
<section class="pt-4">
    <div class="container px-lg-5">
        <!-- Page Features-->
        <div class="row gx-lg-5">
            <div class="col-lg-4 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"></div><br>
                        <a href="{{ url_for('views.view', name = 'jigarbhai') }}">
                            <h2 class="fs-4 fw-bold">JIAGAR BHAI</h2>
                        </a>
                        <p class="mb-0"><b>Saccha Creation</b></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"></div><br>
                        <a href="{{ url_for('views.view', name = 'kartikbhai') }}">
                            <h2 class="fs-4 fw-bold">KARTIK BHAI</h2>
                        </a>
                        <p class="mb-0"><b>Pearl Creation</b></p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-xxl-4 mb-5">
                <div class="card bg-light border-0 h-100">
                    <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"></div><br>
                        <a href="{{ url_for('views.view', name = 'mohanbhai') }}">
                            <h2 class="fs-4 fw-bold">MOHAN BHAI</h2>
                        </a>
                        <p class="mb-0"><b>XYZ Creation</b></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}